name: Deploy to GitHub Pages

on:
  push:
    branches:
<<<<<<< HEAD
      - main  # or your default branch
=======
      - main
>>>>>>> 26bea40 (changes)

jobs:
  deploy:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    permissions:
      contents: write
=======
>>>>>>> 26bea40 (changes)
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

<<<<<<< HEAD
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll

      - name: Add CNAME file
        run: |
          echo "garoono.in" > ./out/CNAME
          touch ./out/.nojekyll

=======
>>>>>>> 26bea40 (changes)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
<<<<<<< HEAD
=======
          cname: ${{ secrets.CNAME }} 
>>>>>>> 26bea40 (changes)
